version: '3'

services:
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # nginx configs
      - ./SSRPanel:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    network:
      - frontend
    depends_on:
      - php

  php:
    restart: always
    build: ./php
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./SSRPanel:/usr/share/nginx/html
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - mysql
      - redis
    network:
      - frontend
      - backend
    environment:
      - TZ='Asia/Shanghai'
      - MIGRATION=true
      - ADMIN_EMAIL=
      - ADMIN_PASS=

      - APP_LANG=en

      - AUTH_SALT=
      - AUTH_PASSWORD_ENCRYPTION_TYPE=bcrypt

      - DB_HOST=mysql
      - DB_DATABASE=sspanel
      - DB_USERNAME=root
      - DB_PASSWORD=sspanel

      - REDIS_HOST=redis

  mysql:
    restart: always
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - TZ='Asia/Shanghai'
      - MYSQL_ROOT_PASSWORD=sspanel
      - MYSQL_DATABASE=sspanel
    volumes:
      - mysql_data:/var/lib/mysql:Z
    network:
      - backend

  redis:
    restart: always
    image: redis:latest
    container_name: redis
    command:
      - --loglevel warning
    volumes:
      - redis_data:/var/lib/redis:Z
    network:
      - backend



network:
  frontend:
  backend:

volumes:
  mysql_data:
  redis_data:
